services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    command: ["redis-server"]

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: example
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U example"]
      interval: 10s
      timeout: 5s
      retries: 5
  # backend:
  #   build:
  #     context: ./BE
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     redis:
  #       condition: service_healthy
  # frontend:
  #   build:
  #     context: ./FE
  #     dockerfile: Dockerfile
  #   ports:
  #     - "4173:4173"
  #   depends_on:
  #     backend:
  #       condition: service_started
