services:
  # redis:
  #   image: redis:latest
  #   ports:
  #     - "6379:6379"
  #   healthcheck:
  #     test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
  #     interval: 1s
  #     timeout: 3s
  #     retries: 5
  #   command: ["redis-server"]

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: example
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U example"]
      interval: 10s
      timeout: 5s
      retries: 5
  # server:
  #   build:
  #     context: ./server
  #     target: final
  #   ports:
  #     - 3001:3001
